scireum/s3ninja

src/main/java/ninja/S3Controller.java, src/main/java/ninja/StoredObject.java
Also fixes parsing of the x-amz-copy-source header
=> Add CopyObject response message XML

pom.xml, src/main/java/ninja/Aws4HashCalculator.java, src/main/java/ninja/AwsHashCalculator.java, src/main/java/ninja/AwsLegacyHashCalculator.java, src/main/java/ninja/S3Controller.java, src/test/groovy/AWSSpec.groovy
I wasn't able to test this since I couldn't pull sirius test kernel JAR but it should work ok - it did in the 2.0 version :)
=> Added bucket delete support, moved AWS hash generation into separate classes

src/main/java/ninja/AwsLegacyHashCalculator.java
=> Fixed legacy hashing method

src/main/java/ninja/Bucket.java, src/main/java/ninja/S3Controller.java, src/main/java/ninja/StoredObject.java
Added support for GET Bucket requests (list contents)
according to http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html
=> Added support for GET Bucket requests (list contents)

src/main/java/ninja/S3Controller.java, src/main/resources/view/api.html
Fixed size in GET bucket output
Added newly supported API calls
=> Fixed size in GET bucket output and added newly supported API calls

pom.xml
Signed-off-by: Andrew Gaul <andrew@gaul.org>
=> Narrow aws-java-sdk dependency to aws-java-sdk-s3

src/main/java/ninja/S3Controller.java
GET at root of service endpoint now returns a list of all buckets: 
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTServiceGET.html
=> Add support for listing buckets

src/main/java/ninja/AwsLegacyHashCalculator.java, src/main/java/ninja/S3Controller.java
See the Request Headers section of [this](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html).
Signed-off by: Isaac Cambron
=> Override headers with URL parameters

pom.xml, src/main/java/ninja/Aws4HashCalculator.java, src/main/java/ninja/AwsLegacyHashCalculator.java, src/main/java/ninja/NinjaController.java, src/main/java/ninja/S3Controller.java, src/main/resources/application.conf, src/test/java/TestSuite.java
Also kept the "ETag" as String in S3Controller.java, because in the new Netty-Version it is "etag" and our current version of the amazon sdk has problems with that
=> Updated sirius-web and sirius-kernel versions

src/main/java/ninja/S3Dispatcher.java
=> Fixes a StringIndexOutOfBoundsException when calling /s3

src/main/java/ninja/NinjaController.java
- Fixes routing of UI upload endpoint
- Route is no longer erroneously forwarded to `S3Dispatcher`
=> Fix UI Upload Endpoint

src/main/java/ninja/Aws4HashCalculator.java
- Adds support for `Authorization` header formatting as sent by more recent versions of `s3cmd`
=> S3CMD Auth Fix

src/main/java/ninja/S3Dispatcher.java
- Transfers etags (base-16-encoded MD5 hashes) in lower case
=> Fix Hashes

src/main/resources/assets/stylesheets/custom.scss
- Fixes menu color (Thank you, @meg1502!)
=> Menu Color

src/main/java/ninja/Bucket.java
=> Fix: Ordering of Keys

src/main/java/ninja/ListFileTreeVisitor.java, src/main/java/ninja/S3Dispatcher.java
> https://scireum.myjetbrains.com/youtrack/issue/SIRI-162
- Uses ISO 8601 formatted dates
Closes #136
=> ISO 8601 Date Format

src/main/java/ninja/S3Dispatcher.java
> https://scireum.myjetbrains.com/youtrack/issue/SIRI-163
- Fixes storage of properties for multipart uploads
=> Fix Properties for Multipart Uploads (SIRI-163)

src/main/java/ninja/S3Dispatcher.java
- Correctly checks authentication hash value
Closes #149.
=> Fix: Authentication Check

pom.xml
[#147 ](https://github.com/scireum/s3ninja/issues/147) fix dependency conflict issue for com.fasterxml.jackson.core:jackson-databind:jar
=> fix dependency conflict issue

src/main/java/ninja/Aws4HashCalculator.java, src/test/java/BaseAWSSpec.groovy
- Encodes spaces as `%20` instead of `+`
Closes #153.
=> Fixes Hashing when Query Contains Space

develop.conf, pom.xml, src/main/java/ninja/NinjaController.java, src/main/resources/application.conf, src/main/resources/extensions/wondergem-page-menu/menu.html.pasta, src/main/resources/templates/api.html.pasta, src/main/resources/templates/bucket.html.pasta, src/main/resources/templates/license.html.pasta, src/main/resources/templates/log.html.pasta
- Upgrades _sirius_ dependencies to latest consistent version
=> Sirius Upgrade

src/main/java/ninja/S3Dispatcher.java, src/main/java/ninja/queries/BucketAclSynthesizer.java, src/main/java/ninja/queries/BucketCorsSynthesizer.java, src/main/java/ninja/queries/BucketLifecycleSynthesizer.java, src/main/java/ninja/queries/BucketLocationSynthesizer.java, src/main/java/ninja/queries/BucketPolicySynthesizer.java, src/main/java/ninja/queries/BucketRequestPaymentSynthesizer.java, src/main/java/ninja/queries/S3QuerySynthesizer.java, src/test/java/BaseAWSSpec.groovy
> https://scireum.myjetbrains.com/youtrack/issue/SIRI-299
- Fixes support for `client.doesBucketExistV2(...)` (which queries ACLs)
- Should enable dependency upgrade of _sirius-biz_
=> Fix: Support for Bucket Check (SIRI-299)

src/main/java/ninja/S3Dispatcher.java, src/test/java/BaseAWSSpec.groovy
> https://scireum.myjetbrains.com/youtrack/issue/SIRI-299
- Properly returns error when attempting to delete a non-existing bucket
=> Fix: Deletion of Non-Existing Buckets (SIRI-299)

src/test/java/BaseAWSSpec.groovy
> https://scireum.myjetbrains.com/youtrack/issue/MISC-24
- Adds test case checking date formatting
- No bug fixes necessary so far, failed to reproduce internally reported error
=> Fix: Date Formatting when Listing Buckets/Bucket Contents (MISC-24)

.drone.yml, Dockerfile
=> change to OpenJDK 17 with a Docker Image for amd64 and arm64 (closes #192)
